import { StyleSheet } from 'react-native';
import { typography } from '../../shared/theme';
import type { Palette } from '../../shared/theme';

export const createStyles = (palette: Palette) => StyleSheet.create({
    page: {
        flex: 1,
        backgroundColor: palette.background,
    },
    header: {
        gap: 16,
        width: `100%`,
        maxWidth: 1200,
        paddingTop: 22,
        paddingBottom: 18,
        paddingHorizontal: 20,
        alignSelf: `center`,
        alignItems: `center`,
        flexDirection: `row`,
        justifyContent: `space-between`,
    },
    headerWide: {
        paddingTop: 28,
        paddingBottom: 24,
        paddingHorizontal: 32,
    },
    brand: {
        gap: 10,
        flexShrink: 0,
        alignItems: `center`,
        flexDirection: `row`,
    },
    logoFrame: {
        width: 42,
        height: 42,
    },
    wordmark: {
        fontSize: 23,
        color: palette.ink,
        fontWeight: `700`,
        letterSpacing: -1,
        fontFamily: typography.display,
    },
    brandText: {
        gap: 3,
    },
    brandTagline: {
        fontSize: 10,
        letterSpacing: 0.1,
        color: palette.muted,
        fontFamily: typography.body,
    },
    headerActions: {
        gap: 14,
        flexShrink: 1,
        alignItems: `center`,
        flexDirection: `row`,
    },
    themeToggle: {
        width: 40,
        height: 40,
        borderWidth: 1,
        borderRadius: 14,
        alignItems: `center`,
        borderColor: palette.line,
        justifyContent: `center`,
        backgroundColor: palette.paper,
    },
    location: {
        gap: 5,
        flexShrink: 1,
        alignItems: `center`,
        flexDirection: `row`,
    },
    locationText: {
        fontSize: 12,
        color: palette.muted,
        fontFamily: typography.body,
    },
    scroll: {
        flex: 1,
    },
    scrollContent: {
        flexGrow: 1,
        paddingVertical: 30,
        paddingHorizontal: 20,
        alignItems: `center`,
        justifyContent: `center`,
    },
    stage: {
        gap: 24,
        width: `100%`,
        maxWidth: 560,
    },
    introduction: {
        gap: 9,
        alignItems: `center`,
    },
    eyebrowRow: {
        gap: 7,
        marginBottom: 4,
        alignItems: `center`,
        flexDirection: `row`,
    },
    localDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: palette.mint,
    },
    eyebrow: {
        fontSize: 10,
        letterSpacing: 2,
        fontWeight: `600`,
        color: palette.muted,
        fontFamily: typography.body,
    },
    heading: {
        fontSize: 28,
        lineHeight: 35,
        textAlign: `center`,
        color: palette.ink,
        letterSpacing: -1.2,
        fontWeight: `700`,
        fontFamily: typography.display,
    },
    headingWide: {
        fontSize: 36,
        lineHeight: 43,
        letterSpacing: -1.6,
    },
    subtitle: {
        fontSize: 12,
        lineHeight: 19,
        textAlign: `center`,
        color: palette.muted,
        fontFamily: typography.body,
    },
    privacy: {
        gap: 6,
        alignItems: `center`,
        flexDirection: `row`,
        justifyContent: `center`,
    },
    privacyText: {
        fontSize: 11,
        color: palette.muted,
        fontFamily: typography.body,
    },
    notice: {
        fontSize: 12,
        paddingVertical: 12,
        paddingHorizontal: 16,
        textAlign: `center`,
        borderRadius: 16,
        color: palette.ink,
        fontFamily: typography.body,
        backgroundColor: palette.softMint,
    },
    bottomNavigation: {
        paddingTop: 10,
        paddingHorizontal: 16,
        backgroundColor: palette.background,
    },
    emptyCard: {
        gap: 12,
        borderWidth: 1,
        minHeight: 300,
        borderRadius: 28,
        paddingVertical: 36,
        paddingHorizontal: 24,
        alignItems: `center`,
        borderColor: palette.line,
        justifyContent: `center`,
        backgroundColor: palette.paper,
    },
    emptyIcon: {
        width: 58,
        height: 58,
        borderRadius: 20,
        marginBottom: 8,
        alignItems: `center`,
        justifyContent: `center`,
        backgroundColor: palette.softMint,
    },
    emptyTitle: {
        fontSize: 20,
        textAlign: `center`,
        color: palette.ink,
        fontWeight: `600`,
        fontFamily: typography.display,
    },
    emptyDescription: {
        fontSize: 13,
        lineHeight: 20,
        textAlign: `center`,
        color: palette.muted,
        fontFamily: typography.body,
    },
    emptyAction: {
        gap: 8,
        minHeight: 44,
        marginTop: 8,
        borderRadius: 14,
        paddingHorizontal: 18,
        alignItems: `center`,
        flexDirection: `row`,
        backgroundColor: palette.softMint,
    },
    emptyActionText: {
        fontSize: 13,
        color: palette.ink,
        fontWeight: `600`,
        fontFamily: typography.body,
    },
    pressed: {
        opacity: 0.7,
    },
});
