import { StyleSheet } from 'react-native';
import { typography, type Palette } from '../../shared/theme';

export const createStyles = (palette: Palette) => StyleSheet.create({
    card: {
        width: `100%`,
        padding: 26,
        maxWidth: 560,
        borderWidth: 1,
        borderRadius: 28,
        borderColor: palette.border,
        backgroundColor: palette.paper,
        boxShadow: `0px 16px 32px ${palette.shadow}`,
    },
    header: {
        gap: 12,
        alignItems: `center`,
        flexDirection: `row`,
        justifyContent: `space-between`,
    },
    headerActions: {
        gap: 2,
        alignItems: `center`,
        flexDirection: `row`,
    },
    community: {
        gap: 12,
        flex: 1,
        alignItems: `center`,
        flexDirection: `row`,
    },
    communityIcon: {
        width: 44,
        height: 44,
        borderRadius: 15,
        alignItems: `center`,
        justifyContent: `center`,
        backgroundColor: palette.paleMint,
    },
    communityDetails: {
        gap: 4,
        flex: 1,
    },
    communityName: {
        fontSize: 15,
        fontWeight: `700`,
        color: palette.ink,
        fontFamily: typography.body,
    },
    meta: {
        fontSize: 11,
        lineHeight: 16,
        color: palette.muted,
        fontFamily: typography.body,
    },
    iconButton: {
        width: 42,
        height: 42,
        borderRadius: 15,
        alignItems: `center`,
        justifyContent: `center`,
    },
    savedButton: {
        backgroundColor: palette.paleMint,
    },
    tag: {
        gap: 6,
        marginTop: 26,
        paddingVertical: 6,
        paddingHorizontal: 10,
        borderRadius: 20,
        alignSelf: `flex-start`,
        alignItems: `center`,
        flexDirection: `row`,
        backgroundColor: palette.paleMint,
    },
    tagDot: {
        width: 5,
        height: 5,
        borderRadius: 3,
        backgroundColor: palette.mint,
    },
    tagLabel: {
        fontSize: 10,
        fontWeight: `600`,
        color: palette.ink,
        letterSpacing: 0.25,
        fontFamily: typography.body,
    },
    body: {
        gap: 16,
        marginTop: 18,
        marginBottom: 28,
    },
    paragraph: {
        fontSize: 23,
        lineHeight: 33,
        letterSpacing: -0.5,
        color: palette.ink,
        fontFamily: typography.display,
    },
    footer: {
        gap: 8,
        paddingTop: 18,
        borderTopWidth: 1,
        alignItems: `center`,
        flexDirection: `row`,
        justifyContent: `flex-end`,
        borderTopColor: palette.border,
    },
    voteControls: {
        padding: 3,
        borderRadius: 24,
        alignItems: `center`,
        flexDirection: `row`,
        backgroundColor: palette.paleMint,
    },
    voteButton: {
        width: 32,
        height: 35,
        borderRadius: 19,
        alignItems: `center`,
        justifyContent: `center`,
    },
    selectedVote: {
        borderWidth: 1,
        borderColor: palette.mint,
        backgroundColor: palette.paper,
    },
    voteScore: {
        fontSize: 13,
        minWidth: 27,
        fontWeight: `700`,
        textAlign: `center`,
        color: palette.ink,
        fontFamily: typography.body,
    },
    repliesButton: {
        gap: 7,
        minHeight: 42,
        borderRadius: 12,
        paddingHorizontal: 3,
        alignItems: `center`,
        flexDirection: `row`,
    },
    repliesLabel: {
        fontSize: 11,
        fontWeight: `500`,
        color: palette.muted,
        fontFamily: typography.body,
    },
    pressed: {
        opacity: 0.6,
    },
    reply: {
        gap: 7,
        padding: 16,
        marginTop: 18,
        borderRadius: 16,
        backgroundColor: palette.paleMint,
    },
    replyAuthor: {
        fontSize: 12,
        fontWeight: `700`,
        color: palette.ink,
        fontFamily: typography.body,
    },
    replyContent: {
        fontSize: 13,
        lineHeight: 20,
        color: palette.ink,
        fontFamily: typography.body,
    },
    replyDemo: {
        fontSize: 10,
        marginTop: 3,
        color: palette.muted,
        fontFamily: typography.body,
    },
});
