import { StyleSheet } from 'react-native';
import { typography, type Palette } from '../../shared/theme';

export const createStyles = (palette: Palette) => StyleSheet.create({
    page: {
        gap: 28,
        width: `100%`,
        maxWidth: 760,
    },
    home: {
        gap: 8,
        minHeight: 44,
        borderWidth: 1,
        borderRadius: 14,
        paddingHorizontal: 14,
        alignSelf: `flex-start`,
        alignItems: `center`,
        flexDirection: `row`,
        borderColor: palette.line,
        backgroundColor: palette.paper,
    },
    homeLabel: {
        fontSize: 12,
        color: palette.ink,
        fontWeight: `600`,
        fontFamily: typography.body,
    },
    introduction: {
        gap: 11,
        paddingHorizontal: 10,
        alignItems: `center`,
    },
    iconFrame: {
        width: 60,
        height: 60,
        borderRadius: 21,
        marginBottom: 6,
        alignItems: `center`,
        justifyContent: `center`,
        backgroundColor: palette.softMint,
    },
    eyebrow: {
        fontSize: 10,
        lineHeight: 15,
        letterSpacing: 2,
        fontWeight: `600`,
        textAlign: `center`,
        color: palette.muted,
        fontFamily: typography.body,
    },
    title: {
        fontSize: 30,
        lineHeight: 37,
        letterSpacing: -1.2,
        fontWeight: `700`,
        color: palette.ink,
        textAlign: `center`,
        fontFamily: typography.display,
    },
    titleWide: {
        fontSize: 38,
        lineHeight: 46,
        letterSpacing: -1.5,
    },
    summary: {
        fontSize: 14,
        lineHeight: 23,
        maxWidth: 560,
        textAlign: `center`,
        color: palette.muted,
        fontFamily: typography.body,
    },
    card: {
        padding: 22,
        borderWidth: 1,
        borderRadius: 28,
        borderColor: palette.line,
        backgroundColor: palette.paper,
        boxShadow: `0px 16px 32px ${palette.shadow}`,
    },
    cardWide: {
        padding: 34,
    },
    note: {
        gap: 10,
        padding: 15,
        borderRadius: 16,
        marginBottom: 8,
        alignItems: `center`,
        flexDirection: `row`,
        backgroundColor: palette.softMint,
    },
    noteDot: {
        width: 6,
        height: 6,
        flexShrink: 0,
        borderRadius: 3,
        backgroundColor: palette.mint,
    },
    noteLabel: {
        flex: 1,
        fontSize: 12,
        lineHeight: 19,
        color: palette.ink,
        fontWeight: `500`,
        fontFamily: typography.body,
    },
    section: {
        gap: 11,
        paddingVertical: 24,
    },
    sectionBorder: {
        borderTopWidth: 1,
        borderTopColor: palette.line,
    },
    sectionTitle: {
        fontSize: 18,
        lineHeight: 26,
        color: palette.ink,
        fontWeight: `600`,
        letterSpacing: -0.4,
        fontFamily: typography.display,
    },
    paragraph: {
        fontSize: 14,
        lineHeight: 24,
        color: palette.muted,
        fontFamily: typography.body,
    },
    pressed: {
        opacity: 0.7,
    },
});
